from __future__ import annotations

import argparse
import json
from pathlib import Path

from mini_drop.analyzer import build_analysis
from mini_drop.perf_importer import load_perf_script


def main() -> None:
    parser = argparse.ArgumentParser(description="Import perf script text into Mini-Drop analyzer JSON.")
    parser.add_argument("perf_script", help="Path to perf.script.txt generated by perf script")
    parser.add_argument("--pid", type=int, default=0)
    parser.add_argument("--task-id", default="perf-script-import")
    parser.add_argument("--out", default="")
    args = parser.parse_args()

    samples = load_perf_script(args.perf_script)
    pid = (args.pid or int(samples[0].get("pid", 0))) if samples else args.pid
    analysis = build_analysis(
        {"id": args.task_id, "pid": pid, "collector": "perf-script-import"},
        samples,
    )
    body = json.dumps({"samples": samples, "analysis": analysis}, ensure_ascii=False, indent=2)
    if args.out:
        Path(args.out).write_text(body + "\n", encoding="utf-8")
    else:
        print(body)


if __name__ == "__main__":
    main()
